### ISSUE TITLE
Question about generating pseudo labels

### ISSUE THREAD

**Issue by YinengXiong** [mrsempress/OBMO_patchnet#2]
Hi，I have a question
In your paper, you only change the camera coord (X, Y, Z) when generating pseudo labels
I wonder why camera coord(X, Y, Z) changed while the objects' size (WHL) keep unchanged ?

**Comment by mrsempress** [comment]
The details can see in our [paper](https://arxiv.org/abs/2212.10049).
The main reason is that the dimension is an inherent property of the object. We do not change it and only focus on predicting the 3D location of the center. We still do the ablation study to prove our idea, as shown in supplementary material Table X. The dimension is **relatively** accurate and is learned stable. Moreover, in many methods, the dimension branch is parallel with other branches. We use statistical priors to predict the dimensions of objects, which means that objects of the same category have similar dimensions. Moreover, the classification task is mature.

**Comment by YinengXiong** [comment]
Thanks, any release plan for the OBMO_GUPNet training code?
