### ISSUE TITLE
使用离线版本的OBMO导致性能下降

### ISSUE THREAD

**Issue by yuxinxin12138** [mrsempress/OBMO_patchnet#3]
尊敬的作者您好，非常感谢您贡献OBMO这样优秀的文章。我在使用离线的OBMO时发现OBMO并没有增强我模型的检测结果，反而导致性能大幅下降，请问是我的操作出现了问题吗？

我的操作：
1. 用我的模型推理产生检测结果
2. 使用offline_OBMO.py，输出我的检测结果以及calib得到data_OBMO_offline
3. 对data_OBMO_offline进行评估

对比：
```shell
Car AP_R40@0.70, 0.70, 0.70:
# 原本的评估结果
3d   AP:18.3453, 14.2495, 11.8751
# 添加OBMO之后得到的评估结果
3d   AP:11.5207, 9.5765, 8.4054
```

**Comment by mrsempress** [comment]
很感谢您对我们工作的认可。
针对您的问题，我们的建议是：
1. 首先确保代码库是否更新到最新版，我们有修正过在offline中的勘误；
2. 查看输入是否有问题（输入为：你的模型产生的检测结果和对应的calib；calib的地址是否正确和对应）
3. 如果以上都没有问题时，尝试调整epsilon参数，或者与我们邮件详细讨论（单从现在的描述来看，我们并不能确认哪里出现了问题）
